# Generated by Django 3.1.4 on 2020-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_author', models.IntegerField(verbose_name='ID автора')),
                ('title', models.CharField(max_length=50, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание объявления')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('geo', models.TextField(verbose_name='Местоположение')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('status', models.BooleanField(verbose_name='Продано')),
                ('id_credit', models.IntegerField(verbose_name='ID условий ипотеки')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
