# Generated by Django 3.1.4 on 2020-12-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание объявления')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('geo', models.TextField(verbose_name='Местоположение')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('status', models.BooleanField(verbose_name='Продано')),
                ('id_credit', models.IntegerField(verbose_name='ID условий ипотеки')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('role', models.CharField(max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Процент под ипотеку')),
                ('id_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ads')),
            ],
            options={
                'verbose_name': 'Условие ипотеки',
                'verbose_name_plural': 'Условия ипотеки',
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.users'),
        ),
    ]
