# Generated by Django 3.1.4 on 2020-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
    ]
