# Generated by Django 3.2.3 on 2021-06-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20210614_1434'),
        ('ad', '0004_auto_20210614_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='current_user',
        ),
        migrations.AddField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
