# Generated by Django 3.2.3 on 2021-06-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20210614_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='id_ad',
            new_name='id',
        ),
    ]
