# Generated by Django 3.2.3 on 2021-06-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_rename_id_ads_id_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='id_ad',
            new_name='id',
        ),
    ]
