# Generated by Django 3.2.3 on 2021-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_alter_ads_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='id',
            new_name='id_ad',
        ),
    ]
