# Generated by Django 3.2.3 on 2021-06-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_rename_id_ads_id_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='author',
        ),
    ]
