# Generated by Django 3.1.4 on 2020-12-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
