# Generated by Django 3.1.4 on 2020-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.TextField(verbose_name='Название документа'),
        ),
    ]
