# Generated by Django 3.2.3 on 2021-06-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_answers_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='id',
            new_name='current_user',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='id',
            new_name='current_user',
        ),
    ]
