# Generated by Django 3.2.3 on 2021-06-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210614_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
    ]
