# Generated by Django 3.2.3 on 2021-06-14 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210614_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='id_blog',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='id_question',
            new_name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
