# Generated by Django 3.2.3 on 2021-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='id',
            new_name='id_answer',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='id',
            new_name='id_article',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='id',
            new_name='id_blog',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='id',
            new_name='id_document',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='id',
            new_name='id_job',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='id',
            new_name='id_new',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='id',
            new_name='id_question',
        ),
    ]
